name: payrolldb
version: '1.0'
profile: payrolldb_profile
model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

# Define model configurations
models:
  payrolldb:
    warehouse:
      +materialized: incremental  # Ensures models use incremental strategy
      +schema: edw
      +incremental_strategy: merge  # Defines the merge strategy for incremental models
      # Define unique keys for incremental models
      fact_payroll:
        +unique_key: PayrollID
      dim_employee:
        +incremental_strategy: merge
        +unique_key: EmployeeID
      dim_agency:
        +incremental_strategy: merge
        +unique_key: AgencyID
      dim_title:
        +incremental_strategy: merge
        +unique_key: TitleCode
    marts:
      # Configuration for marts models
      +materialized: incremental
      +incremental_strategy: merge
      +schema: marts
      # Define unique keys for incremental models in marts
      overtime_by_employee_and_agency:
        +unique_key: (EmployeeID, AgencyID)
      payroll_aggregate_by_agency:
        +unique_key: (AgencyID, FiscalYear)
