name: payrolldb
version: 1.0
profile: payrolldb_profile
model-paths: ["models"]

models:
  payrolldb:
    staging:
      materialized: view
      schema: stg
    warehouse:
      materialized: incremental
      schema: edw
      +incremental_strategy: merge

seeds:
  quote_columns: True

tests:
  severity: error
