# Dockerfile.etl_monitor

FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the script and any necessary files
COPY helpers/metrics_server.py ./

# Install the prometheus_client directly
RUN pip install prometheus_client

# Expose the port the metrics server will run on
EXPOSE 8000

# Command to run the metrics server
CMD ["python", "metrics_server.py"]