version: '3.8'

services:
  airflow:
    image: puckel/docker-airflow:1.10.9
    container_name: airflow_container
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
      - ./airflow/config:/usr/local/airflow/config
      - ./logs:/usr/local/airflow/logs
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./airflow/config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3000:3000"
    volumes:
      - ./airflow/config/grafana.ini:/etc/grafana/grafana.ini
