version: '3.9'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    restart: always
    environment:
      - PYTHONPATH=/opt/airflow/dags:/opt/airflow/helpers:/opt/airflow/scripts 
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - DBT_PROFILES_DIR=/opt/airflow/dbt
      # SMTP email environment variables
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_STARTTLS=${SMTP_STARTTLS}
      - SMTP_SSL=${SMTP_SSL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_MAIL_FROM=${SMTP_MAIL_FROM}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./dbt:/opt/airflow/dbt
      - ./helpers:/opt/airflow/helpers
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
      - grafana
      - etl_monitor
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  etl_monitor:
    build:
      context: .
      dockerfile: Dockerfile.etl_monitor
    container_name: etl_monitor
    ports:
      - "8000:8000"
    networks:
      - monitoring

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
