global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'metrics_server'
    static_configs:
      - targets: ['metrics_server:8000']
