version: 2

sources:
  - name: stg
    schema: stg
    description: "Staging schema containing raw data"
    tables:
      - name: staging_fact_payroll
        description: "Staged payroll data"
      - name: staging_dim_employee
        description: "Staged employee data"
      - name: staging_dim_agency
        description: "Staged agency data"
      - name: staging_dim_title
        description: "Staged title data"

  - name: edw
    schema: edw
    description: "Data warehouse schema"
    tables:
      - name: dim_date
        description: "Date dimension table"

models:
  - name: dim_employee
    description: "Dimension table for employees"
    columns:
      - name: EmployeeID
        tests:
          - unique
          - not_null
      - name: FirstName
        tests:
          - not_null
      - name: LastName
        tests:
          - not_null
      - name: LeaveStatusasofJune30
        tests:
          - not_null

  - name: dim_agency
    description: "Dimension table for agencies"
    columns:
      - name: AgencyID
        tests:
          - unique
          - not_null
      - name: AgencyName
        tests:
          - not_null

  - name: dim_title
    description: "Dimension table for titles"
    columns:
      - name: TitleCode
        tests:
          - unique
          - not_null
      - name: TitleDescription
        tests:
          - not_null

  - name: fact_payroll
    description: "Fact table for payroll data"
    columns:
      - name: PayrollID
        tests:
          - unique
          - not_null
      - name: PayrollNumber
        tests:
          - not_null
      - name: EmployeeID
        tests:
          - not_null
      - name: AgencyID
        tests:
          - not_null
      - name: TitleCode
        tests:
          - not_null
      - name: DateID
        tests:
          - not_null
      - name: BaseSalary
        tests:
          - not_null
      - name: RegularHours
        tests:
          - not_null
      - name: RegularGrossPaid
        tests:
          - not_null
      - name: OTHours
        tests:
          - not_null
      - name: TotalOTPaid
        tests:
          - not_null
      - name: TotalOtherPay
        tests:
          - not_null
      - name: WorkLocationBorough
        tests:
          - not_null
