version: 2

models:
  - name: stg_fact_payroll
    description: "Staging table for raw payroll data"
    columns:
      - name: PayrollNumber
        tests:
          - not_null
      - name: EmployeeID
        tests:
          - not_null
      - name: FiscalYear
        tests:
          - not_null
      - name: BaseSalary
        tests:
          - not_null
      - name: RegularHours
        tests:
          - not_null
      - name: RegularGrossPaid
        tests:
          - not_null
      - name: OTHours
        tests:
          - not_null
      - name: TotalOTPaid
        tests:
          - not_null
      - name: TotalOtherPay
        tests:
          - not_null
      - name: WorkLocationBorough
        tests:
          - not_null

  - name: stg_dim_employee
    description: "Staging table for raw employee dimension data"
    columns:
      - name: EmployeeID
        tests:
          - unique
          - not_null
      - name: LastName
        tests:
          - not_null
      - name: FirstName
        tests:
          - not_null

  - name: stg_dim_agency
    description: "Staging table for raw agency dimension data"
    columns:
      - name: AgencyID
        tests:
          - unique
          - not_null
      - name: AgencyName
        tests:
          - not_null

  - name: stg_dim_title
    description: "Staging table for raw title dimension data"
    columns:
      - name: TitleCode
        tests:
          - unique
          - not_null
      - name: TitleDescription
        tests:
          - not_null
